### ISSUE TITLE
suggestion on optimization:check_fs_blocklist 

### ISSUE THREAD

**Issue by qqbbddpp** [CoolerVoid/casper-fs#2]
It's great to see your project casper-fs.I found a problem,in file hooked.h,The check_fs_blocklist function deals with relative paths,if i excute rm -f ../myfolder/backup_httpd.log,check_fs_blocklist function will not protect file backup_httpd.log，because the files to be protected in list are backup_httpd.log.so i suggest kernel_filename can be a real path or you can compare file inodes.

                                                                                                                                                my email :
                                                                                                                                                george901112@126.com

**Comment by CoolerVoid** [comment]
Thank you for your feedback, so one solution is to insert the directory name in the YAML rule file.

I need to review and test the action of recursive content removal, but I believe if you insert a rule to protect a directory, and generate LKM code can solve the problem.
